#!/bin/sh

source alba_blissrc

if [ "$USER" = "srubio" ] ; then
        APP_FOLDER=/home/srubio/PROJECTS/GUIs/Vacca
else
        APP_FOLDER=/homelocal/sicilia/applications/vacca
fi
WORKING_DIR=/data/Vacuum

echo "The application folders are $APP_FOLDER and $WORKING_DIR"
#cd $WORKING_DIR

FAST=`echo $1$2 | grep 'fast'`
CLASSIC=`echo $1$TANGO_HOST | grep 'alba03\|classic'`
echo $FAST
echo $CLASSIC
echo ...
if [ "$FAST" == "" ] && [ "$CLASSIC" != "" ] ; then
    export PYTHONPATH=$APP_FOLDER:$PYTHONPATH
    case "$TANGO_HOST" in
        'tbl0401:10000')
            ARGS='BL04/bl04.rc.py'
            ;;
        'tbl0901:10000')
            ARGS='BL09/bl09.rc.py'
            ;;
        'tbl1101:10000')
            ARGS='BL11/bl11.rc.py'
            ;;
        'tbl1301:10000')
            ARGS='BL13/bl13.rc.py'
            ;;
        'tbl2201:10000')
            ARGS='BL22/bl22.rc.py'
            ;;
        'tbl2401:10000')
            ARGS='BL24/bl24.rc.py'
            ;;
        'tbl2901:10000')
            ARGS='BL29/bl29.rc.py'
            ;;
        'alba03:10000')
            ARGS='etc/sr.rc.py'
            ;;
    esac
    /usr/bin/python $APP_FOLDER/vacca.py $ARGS $FAST
else
 vaccagui
fi

#case "$1" in
#'fast'|'--fast')
# /usr/bin/python $APP_FOLDER/vacca.py $2 $3 --fast
# ;;
#*)
# /usr/bin/python $APP_FOLDER/vacca.py $*
# ;;
#esac
